"""YouTube 업로드. OAuth 인증 + 영상 업로드 + 메타데이터 + Gate 6 검증."""

import re
from pathlib import Path

from googleapiclient.discovery import build
from googleapiclient.errors import HttpError
from googleapiclient.http import MediaFileUpload
from google.auth.transport.requests import Request
from google.oauth2.credentials import Credentials
from google_auth_oauthlib.flow import InstalledAppFlow
from rich.console import Console
from rich.progress import Progress

from song_maker import config as cfg
from song_maker.gates import Check, GateResult
from song_maker.models import Song

console = Console()

SCOPES = [
    "https://www.googleapis.com/auth/youtube.upload",
    "https://www.googleapis.com/auth/youtube",
]

TOKEN_PATH = cfg.CONFIG_DIR / "token.json"
CLIENT_SECRET_PATH = cfg.CONFIG_DIR / "client_secret.json"


def authenticate() -> Credentials:
    """OAuth 2.0 인증. 토큰 저장/자동 갱신."""
    creds = None

    if TOKEN_PATH.exists():
        creds = Credentials.from_authorized_user_file(str(TOKEN_PATH), SCOPES)

    if creds and creds.valid:
        return creds

    if creds and creds.expired and creds.refresh_token:
        try:
            creds.refresh(Request())
            _save_token(creds)
            return creds
        except Exception:
            pass  # 갱신 실패 시 재인증

    if not CLIENT_SECRET_PATH.exists():
        raise FileNotFoundError(
            f"OAuth 클라이언트 파일이 없습니다: {CLIENT_SECRET_PATH}\n"
            f"Google Cloud Console에서 다운로드 후 위 경로에 복사하세요."
        )

    flow = InstalledAppFlow.from_client_secrets_file(str(CLIENT_SECRET_PATH), SCOPES)
    creds = flow.run_local_server(port=0)
    _save_token(creds)
    return creds


def _save_token(creds: Credentials) -> None:
    """토큰을 파일에 저장. 소유자만 읽기/쓰기 가능."""
    cfg.CONFIG_DIR.mkdir(parents=True, exist_ok=True)
    TOKEN_PATH.write_text(creds.to_json())
    try:
        TOKEN_PATH.chmod(0o600)
    except OSError:
        # Windows 등 chmod 미지원 환경은 무시
        pass


def generate_title(song: Song) -> str:
    """곡 메타데이터로 YouTube 제목 생성."""
    return f"{song.theme} | {song.genre}"


def generate_description(song: Song, song_dir: Path) -> str:
    """곡 메타데이터 + 가사로 YouTube 설명 생성."""
    lines = [
        f"🎵 {song.theme}",
        "",
        f"장르: {song.genre}",
        f"분위기: {song.mood}",
        "",
    ]

    lyrics_path = song_dir / (song.lyrics_path or "lyrics.txt")
    if lyrics_path.exists():
        lyrics = lyrics_path.read_text(encoding="utf-8").strip()
        if lyrics:
            lines.append("--- 가사 ---")
            lines.append(lyrics)
            lines.append("")

    lines.append("Generated by Song Maker")
    return "\n".join(lines)


def generate_tags(song: Song) -> list[str]:
    """곡 메타데이터로 YouTube 태그 생성."""
    tags = [song.genre, song.mood, song.theme]
    tags.extend(song.lyrics_keywords)
    tags.extend(["AI music", "AI 음악", "Song Maker"])
    return [t for t in tags if t][:30]


def upload(
    song: Song,
    song_dir: Path,
    privacy: str = "private",
) -> Song:
    """영상을 YouTube에 업로드한다."""
    creds = authenticate()
    youtube = build("youtube", "v3", credentials=creds)

    video_path = song_dir / (song.video_path or "video.mp4")
    if not video_path.exists():
        raise FileNotFoundError(f"영상 파일 없음: {video_path}")

    title = generate_title(song)
    description = generate_description(song, song_dir)
    tags = generate_tags(song)

    body = {
        "snippet": {
            "title": title,
            "description": description,
            "tags": tags,
            "categoryId": "10",  # Music
        },
        "status": {
            "privacyStatus": privacy,
            "selfDeclaredMadeForKids": False,
        },
    }

    media = MediaFileUpload(
        str(video_path),
        mimetype="video/mp4",
        resumable=True,
        chunksize=256 * 1024,
    )

    request = youtube.videos().insert(
        part="snippet,status",
        body=body,
        media_body=media,
    )

    # Resumable upload
    response = None
    with Progress() as progress:
        task = progress.add_task("YouTube 업로드 중...", total=100)
        while response is None:
            status, response = request.next_chunk()
            if status:
                percent = int(status.progress() * 100)
                progress.update(task, completed=percent)
        progress.update(task, completed=100)

    video_id = response["id"]
    youtube_url = f"https://youtu.be/{video_id}"

    # 썸네일 설정
    thumb_path = song_dir / (song.thumbnail_path or "thumbnail.png")
    if thumb_path.exists():
        try:
            youtube.thumbnails().set(
                videoId=video_id,
                media_body=MediaFileUpload(str(thumb_path), mimetype="image/png"),
            ).execute()
        except HttpError as e:
            if e.resp.status == 403:
                console.print("  [yellow][경고][/yellow] 썸네일 설정 실패. YouTube 계정 인증을 확인하세요.")
            else:
                console.print(f"  [yellow][경고][/yellow] 썸네일 설정 실패: {e}")

    song.youtube_url = youtube_url
    song.status = "uploaded"
    from datetime import datetime
    song.uploaded_at = datetime.now()

    return song


def upload_capcut(
    mp4_path: Path,
    meta: dict,
    *,
    privacy: str = "private",
    thumbnail_path: Path | None = None,
) -> str:
    """CapCut export mp4를 YouTube에 업로드.

    Args:
        mp4_path: CapCut에서 export한 mp4 파일
        meta: youtube_meta.json 내용 (title, description, tags, timeline, localizations)
        privacy: private/unlisted/public
        thumbnail_path: 썸네일 png 경로 (선택)

    Returns:
        YouTube URL
    """
    if not mp4_path.exists():
        raise FileNotFoundError(f"mp4 파일 없음: {mp4_path}")

    creds = authenticate()
    youtube = build("youtube", "v3", credentials=creds)

    title = meta.get("youtube_title") or meta.get("suno_title") or mp4_path.stem
    description = meta.get("youtube_description") or ""

    # 타임라인이 있으면 description 앞에 chapters 형식으로 추가
    timeline = meta.get("timeline") or []
    if timeline:
        chapter_lines = []
        for entry in timeline:
            if isinstance(entry, dict):
                ts = entry.get("timestamp", "")
                label = entry.get("label", "")
                if ts and label:
                    chapter_lines.append(f"{ts} {label}")
            elif isinstance(entry, str):
                chapter_lines.append(entry)
        if chapter_lines:
            description = "\n".join(chapter_lines) + "\n\n" + description

    tags = meta.get("youtube_tags") or []
    if isinstance(tags, str):
        tags = [t.strip() for t in tags.split(",") if t.strip()]

    body: dict = {
        "snippet": {
            "title": title[:100],  # YouTube 제목 100자 한도
            "description": description[:5000],  # 본문 5000자 한도
            "tags": tags[:30],
            "categoryId": "10",  # Music
        },
        "status": {
            "privacyStatus": privacy,
            "selfDeclaredMadeForKids": False,
        },
    }

    # 다국어 localizations
    localizations = meta.get("localizations") or {}
    if localizations:
        body["localizations"] = {
            lang: {
                "title": (data.get("title") or title)[:100],
                "description": (data.get("description") or description)[:5000],
            }
            for lang, data in localizations.items()
            if isinstance(data, dict)
        }

    parts = "snippet,status"
    if "localizations" in body:
        parts += ",localizations"

    media = MediaFileUpload(
        str(mp4_path),
        mimetype="video/mp4",
        resumable=True,
        chunksize=256 * 1024,
    )

    request = youtube.videos().insert(
        part=parts,
        body=body,
        media_body=media,
    )

    response = None
    with Progress() as progress:
        task = progress.add_task("YouTube 업로드 중...", total=100)
        while response is None:
            status, response = request.next_chunk()
            if status:
                percent = int(status.progress() * 100)
                progress.update(task, completed=percent)
        progress.update(task, completed=100)

    video_id = response["id"]
    youtube_url = f"https://youtu.be/{video_id}"

    # 썸네일 설정
    if thumbnail_path and thumbnail_path.exists():
        try:
            youtube.thumbnails().set(
                videoId=video_id,
                media_body=MediaFileUpload(str(thumbnail_path), mimetype="image/png"),
            ).execute()
        except HttpError as e:
            console.print(f"  [yellow][경고][/yellow] 썸네일 설정 실패: {e}")

    return youtube_url


def set_public(video_id: str) -> None:
    """영상을 공개로 전환한다."""
    creds = authenticate()
    youtube = build("youtube", "v3", credentials=creds)
    youtube.videos().update(
        part="status",
        body={
            "id": video_id,
            "status": {"privacyStatus": "public"},
        },
    ).execute()


def verify_gate6(song: Song) -> GateResult:
    """Gate 6: 유튜브 업로드 결과 검증."""
    checks: list[Check] = []

    # 6-2. YouTube URL
    url = song.youtube_url or ""
    url_valid = bool(re.match(r"https://(youtu\.be/|www\.youtube\.com/watch\?v=)\S+", url))
    checks.append(Check(
        name="youtube_url",
        passed=url_valid,
        message=f"YouTube URL이 유효하지 않습니다: {url}",
    ))

    # 6-3. 상태
    checks.append(Check(
        name="upload_status",
        passed=song.status == "uploaded",
        message="업로드 상태가 'uploaded'가 아닙니다.",
    ))

    # 6-4. 업로드 시간 (비차단)
    checks.append(Check(
        name="uploaded_at",
        passed=song.uploaded_at is not None,
        blocking=False,
        message="업로드 시간이 기록되지 않았습니다.",
    ))

    return GateResult(gate="gate6", checks=checks)
